Enhanced the local_integration_test script

diff --git a/.ci/local_integration_test b/.ci/local_integration_test
--- a/.ci/local_integration_test
+++ b/.ci/local_integration_test
@@ -7,22 +7,224 @@ set -e
 # For the test step concourse will set the following environment variables:
 # SOURCE_PATH - path to component repository root directory.
 
-mcm_repo_link="dev/mcm"
-if [[ ! -d "$mcm_repo_link" ]]; then
-  echo "Error: MCM Repo expected at: $mcm_repo_link
-    For running local Integration Tests, kindly checkout MCM Repo locally and execute 'ln -sf <absolutePathToMcmRepo> $mcm_repo_link'"
+mcm_repo_link="dev"
+declare TARGET_CLUSTER
+declare PROJECT
+
+printf "\e[34mDo you want to clone the latest MCM Repo? (true/false)\e[0m\n"
+read clone_mcm_repo
+
+#check if clone_mcm_repo is not empty
+if [ -z "$clone_mcm_repo" ]
+then
+      printf "\e[31mentered value cannot be empty\e[0m\n"
+      exit 1
+fi
+
+#check if clone_mcm_repo is a boolean
+if [ "$clone_mcm_repo" != true ] && [ "$clone_mcm_repo" != false ]
+then
+      printf "\e[31mentered value must be a boolean\e[0m\n"
+      exit 1
+fi
+
+if [ "$clone_mcm_repo" = true ]
+then
+    if [ ! -d "$mcm_repo_link" ]
+    then
+        mkdir -p $mcm_repo_link
+    fi
+    cd $mcm_repo_link
+    git clone https://github.com/gardener/machine-controller-manager
+    mv machine-controller-manager mcm
+    cd -
+fi
+
+
+if [[ ! -d "$mcm_repo_link/mcm" ]]; then
+  echo "Error: MCM Repo expected at: $mcm_repo_link/mcm
+    For running local Integration Tests, kindly checkout MCM Repo locally and execute 'ln -sf <absolutePathToMcmRepo> $mcm_repo_link/dev'"
   exit 1
 fi
 
 cd test/integration/controller
 if ! hash ginkgo; then
-	# Install Ginkgo (test framework) to be able to execute the tests.
-	echo "Fetching Ginkgo frawework"
-	go install github.com/onsi/ginkgo/v2/ginkgo
-	echo "Successfully fetched Ginkgo frawework"
-	ginkgo version
+        # Install Ginkgo (test framework) to be able to execute the tests.
+        echo "Fetching Ginkgo frawework"
+        go install github.com/onsi/ginkgo/v2/ginkgo
+        echo "Successfully fetched Ginkgo frawework"
+        ginkgo version
 fi
 
-echo "Starting integration tests..."
+printf  "\e[34mIs the control cluster a seed? (true/false)\e[0m\n"
+read IS_CONTROL_CLUSTER_SEED
 
-ginkgo -v --show-node-events --poll-progress-after=480s --poll-progress-interval=90s
+if [ -z "$IS_CONTROL_CLUSTER_SEED" ]
+then
+      printf "\e[31mentered value cannot be empty\e[0m\n"
+      exit 1
+fi
+
+if [ "$IS_CONTROL_CLUSTER_SEED" != true ] && [ "$IS_CONTROL_CLUSTER_SEED" != false ]
+then
+      printf "\e[31mentered value must be a boolean\e[0m\n"
+      exit 1
+fi
+export IS_CONTROL_CLUSTER_SEED=$IS_CONTROL_CLUSTER_SEED
+
+printf "\e[34mEnter the absolute path to the local machine-controller-manager repository.\e[0m\n"
+
+read MCM_REPO_PATH
+if [ -z "$MCM_REPO_PATH" ]
+then
+      printf "\e[31mentered value cannot be empty\e[0m\n"
+      exit 1
+fi
+if [ ! -d "$MCM_REPO_PATH" ]
+then
+      printf "\e[31m$MCM_REPO_PATH is not a valid directory\e[0m\n"
+      exit 1
+fi
+
+if [ "$IS_CONTROL_CLUSTER_SEED" = true ]
+then
+    echo "Enter the target cluster"
+    read TARGET_CLUSTER
+    if [ -z "$TARGET_CLUSTER" ]
+    then
+        printf "\e[31mtarget cluster cannot be empty\e[0m\n"
+        exit 1
+    fi
+    echo "Enter the project name"
+    read PROJECT
+    if [ -z "$TARGET_CLUSTER" ]
+    then
+        printf "\e[31mtarget cluster cannot be empty\e[0m\n"
+        exit 1
+    fi
+    cd $MCM_REPO_PATH
+    make gardener-setup
+    cd -
+else
+    cd $MCM_REPO_PATH
+    echo "Enter the project"
+    read PROJECT
+    if [ -z "$PROJECT" ]
+    then
+        printf "\e[31mproject cannot be empty\e[0m\n"
+        exit 1
+    fi
+    echo "Enter the control cluster"
+    read CONTROL_CLUSTER
+    if [ -z "$CONTROL_CLUSTER" ]
+    then
+        printf "\e[31mcontrol cluster cannot be empty\e[0m\n"
+        exit 1
+    fi
+    echo "Enter the target cluster"
+    read TARGET_CLUSTER
+    if [ -z "$TARGET_CLUSTER" ]
+    then
+        printf "\e[31mtarget cluster cannot be empty\e[0m\n"
+        exit 1
+    fi
+    echo "Enter the machine class file path"
+    read MACHINECLASS
+    if [ ! -f "$MACHINECLASS" ]
+    then
+        printf "\e[31m$MACHINECLASS is not a valid file path\e[0m\n"
+        exit 1
+    fi
+    make non-gardener-setup
+    cd -
+    cd ../../..
+    printf "\n%s" "MACHINECLASS_V1=${MACHINECLASS}" >> ".env"
+    cd test/integration/controller
+fi
+
+cd ../../..
+printf "\n%s" "TARGET_CLUSTER_NAME=shoot--${PROJECT}--${TARGET_CLUSTER}" >> ".env"
+set -o allexport
+source .env
+set +o allexport
+cd test/integration/controller
+
+CREDENTIALS_SECRET_NAME=shoot-operator-az-team
+GARDEN_CORE_NAMESPACE=garden-core
+
+function fetch_userdata(){
+    NAMESPACE='garden'
+    USERDATA_SECRET_NAME=$(kubectl get secrets -o custom-columns=Name:.metadata.name --no-headers | grep shoot--$PROJECT | head -n 1)
+    kubectl get secret $USERDATA_SECRET_NAME -oyaml > userData.yaml
+    userData=$(yq eval '.data.userData' userData.yaml)
+    echo $userData
+}
+
+
+function fetch_credentials(){
+   kubectl get secret $CREDENTIALS_SECRET_NAME -n $GARDEN_CORE_NAMESPACE -o yaml > credentials.yaml
+   clientID=$(yq eval '.data.clientID' credentials.yaml)
+   clientSecret=$(yq eval '.data.clientSecret' credentials.yaml)
+   subscriptionID=$(yq eval '.data.subscriptionID' credentials.yaml)
+   tenantID=$(yq eval '.data.tenantID' credentials.yaml)
+
+   # The below echo is re-directed to variable and not printed.
+   echo "$clientID" "$clientSecret" "$subscriptionID" "$tenantID"
+}
+
+function create_test_mc_secret() {
+  gardenctl target --garden sap-landscape-dev
+  eval $(gardenctl kubectl-env bash)
+  read clientID clientSecret subscriptionID tenantID < <(fetch_credentials)
+  gardenctl target --garden sap-landscape-dev --project $PROJECT --shoot $TARGET_CLUSTER --control-plane
+  eval $(gardenctl kubectl-env bash)
+  userData=$(fetch_userdata)
+  rm -f credentials.yaml
+  rm -f userData.yaml
+secret_yaml=$(cat <<EOF
+apiVersion: v1
+data:
+  clientID: $clientID
+  clientSecret: $clientSecret
+  subscriptionID: $subscriptionID
+  tenantID: $tenantID
+  userData: $userData
+kind: Secret
+metadata:
+  name: test-mc-secret
+  namespace: default
+type: Opaque
+EOF
+)
+    gardenctl target --garden sap-landscape-dev --project $PROJECT --shoot $CONTROL_CLUSTER
+    eval $(gardenctl kubectl-env bash)
+    echo "$secret_yaml" | kubectl  apply -f -
+}
+
+if [ "$IS_CONTROL_CLUSTER_SEED" = false ]
+then
+  create_test_mc_secret
+  printf "\e[32mSuccessfully created test_mc_secret on control cluster\e[0m\n"
+fi
+
+printf "\e[33mStarting integration tests...\e[0m\n"
+
+set +e
+ginkgo -v --show-node-events --poll-progress-after=300s --poll-progress-interval=60s
+set -e
+printf "\e[32mIntegration tests completed successfully\e[0m\n"
+
+if [ "$IS_CONTROL_CLUSTER_SEED" = false ]
+then
+  set +e
+  gardenctl target --garden sap-landscape-dev --project $PROJECT --shoot $CONTROL_CLUSTER
+  eval $(gardenctl kubectl-env bash)
+  kubectl delete secret test-mc-secret
+  set -e
+  printf "\e[32mSuccessfully deleted test-mc-secret on control cluster\e[0m\n"
+fi
+
+cd ../../..
+rm -f .env
+cd test/integration/controller
+
