[ci:component:github.com/gardener/machine-controller-manager:v0.49.1->v0.51.1] (#127)
* Upgrade github_com_gardener_machine-controller-manager

from v0.49.1 to v0.51.1

* adopt to mcm 0.51.1 - ginkgov2,Makefile,env,pipeline IT

* change to az-ci-it

* log added for debugging

* added tracing

* echoing fetch_service_account_kubeconfig

* added print for dev/sa_kubeconfig.yaml

* debug rawUrl

* test_mc_secret debugging

* removed print of request_kubeconfig

* removed log for request_kubeconfig

* removed log for request_kubeconfig

* removed secret print

* Update .ci/pipeline_integration_test

removed debugging echo

Co-authored-by: Rishabh Patel <66425093+rishabh-11@users.noreply.github.com>

* Update .ci/pipeline_integration_test

Co-authored-by: Rishabh Patel <66425093+rishabh-11@users.noreply.github.com>

* added comment for redirected echo

* Update .ci/pipeline_integration_test

removed debugging of kubeconfigs

Co-authored-by: Rishabh Patel <66425093+rishabh-11@users.noreply.github.com>

---------

Co-authored-by: gardener-robot-ci-2 <gardener.ci.user2@gmail.com>
Co-authored-by: elankath <tarun.ramakrishna.elankath@sap.com>
Co-authored-by: Rishabh Patel <66425093+rishabh-11@users.noreply.github.com>

diff --git a/.ci/pipeline_integration_test b/.ci/pipeline_integration_test
--- a/.ci/pipeline_integration_test
+++ b/.ci/pipeline_integration_test
@@ -9,15 +9,23 @@ logs_path=.ci/controllers-test/logs
 TEST_RESULT=
 cli_path=/cc/utils/cli.py
 num_of_existing_nodes=1
+CREDENTIALS_SECRET_NAME=shoot-operator-az-team
+GARDEN_CORE_NAMESPACE=garden-core
+KUBECONFIG_EXPIRY=10800
 
 #these variables are accessed in test/integration/controller so prefixed by ${SOURCE_PATH} for absolute path
 declare CONTROL_KUBECONFIG=${SOURCE_PATH}/dev/control_kubeconfig.yaml
 declare TARGET_KUBECONFIG=${SOURCE_PATH}/dev/target_kubeconfig.yaml
+declare TEST_SHOOT=az-ci-it
+declare TEST_CREDS_SECRET=test-mc-secret
+declare TARGET_RESOURCE_GROUP="shoot--mcm-ci--$TEST_SHOOT"
 
 export CONTROL_KUBECONFIG
 export TARGET_KUBECONFIG
+export TEST_CREDS_SECRET
 export MACHINECLASS_V1=${SOURCE_PATH}/dev/v1machineclass_converted.yaml
 export MACHINE_CONTROLLER_MANAGER_DEPLOYMENT_NAME="machine-controller-manager"
+export TARGET_RESOURCE_GROUP
 
 ############################################## <Helper fn> ##############################################
 
@@ -42,6 +50,7 @@ function hf_num_of_ready_nodes() {
 }
 
 function hf_wait_on() {
+    wait_interval=30
     function_name=$1
     function_param=$2
     count_to_match=$3
@@ -53,7 +62,8 @@ function hf_wait_on() {
         ret=$?
         [[ $ret -ne $count_to_match ]]
     do
-        sleep 30
+        printf "\n\t Error: %s invoked with %s did not return expected value %s. Will retry again in %s...\n" "$function_name" "$function_param" "$count_to_match" "$ wait_interval"
+        sleep $wait_interval
         ((iteration_count--))
 
         # Exit script when timeout occurs
@@ -74,25 +84,96 @@ function hf_wait_on() {
 
 function setup_ginkgo() {
     echo "Installing Ginkgo..."
-    GO111MODULE=off go get -u github.com/onsi/ginkgo/ginkgo
+	  go install github.com/onsi/ginkgo/v2/ginkgo
     ginkgo version
     echo "Successfully installed Ginkgo."
 }
 
-function fetch_control_kubeconfig() {
-    ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-az-oot-control --key kubeconfig  > dev/control_kubeconfig.yaml
+function fetch_service_account_kubeconfig() {
+    echo "fetch_service_account_kubeconfig: ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-garden-dev-virtual --key kubeconfig  > dev/sa_kubeconfig.yaml"
+    ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-garden-dev-virtual --key kubeconfig  > dev/sa_kubeconfig.yaml
 }
 
-function fetch_target_kubeconfig() {
-    ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-az-oot-target --key kubeconfig > dev/target_kubeconfig.yaml
+function request_kubeconfig() {
+    rawUrl="/apis/core.gardener.cloud/v1beta1/namespaces/$1/shoots/$2/adminkubeconfig"
+    kubectl --kubeconfig=dev/sa_kubeconfig.yaml create -f <(printf '{"spec":{"expirationSeconds":%s}}' $KUBECONFIG_EXPIRY) --raw "$rawUrl" | jq -r ".status.kubeconfig" | base64 -d  > "$3"
 }
 
-function fetch_machine_class() {
-    #bringing machineclass from secret server
-    ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-az-oot-target --key machineClass > ${SOURCE_PATH}/dev/v1machineclass.json
+# Fetch *-ci-it cluster kubeconfig
+function fetch_oot_cluster_kubeconfig() {
+    NAMESPACE=garden-mcm-ci
+    request_kubeconfig "$NAMESPACE" "$TEST_SHOOT" "dev/target_kubeconfig.yaml"
+    request_kubeconfig "$NAMESPACE" "$TEST_SHOOT" "dev/control_kubeconfig.yaml"
+}
 
-    #convert json to yaml, so that machineclass can be parsed during integration-test
-    yq e -P ${SOURCE_PATH}/dev/v1machineclass.json > ${SOURCE_PATH}/dev/v1machineclass_converted.yaml
+function fetch_userdata(){
+    NAMESPACE='garden'
+    kubectl --kubeconfig=dev/sa_kubeconfig.yaml get shoot $TEST_SHOOT -oyaml > dev/shoot.yaml
+    SEED_NAME=$(yq eval '.status.seedName' dev/shoot.yaml)
+    request_kubeconfig $NAMESPACE $SEED_NAME "dev/seed_kubeconfig.yaml"
+    USERDATA_SECRET_NAME=$(kubectl --kubeconfig=dev/seed_kubeconfig.yaml get secrets -n shoot--mcm-ci--$TEST_SHOOT -o custom-columns=Name:.metadata.name --no-headers | grep shoot--mcm-ci)
+    kubectl --kubeconfig=dev/seed_kubeconfig.yaml get secret $USERDATA_SECRET_NAME -n shoot--mcm-ci--$TEST_SHOOT -oyaml > dev/userData.yaml
+    userData=$(yq eval '.data.userData' dev/userData.yaml)
+
+    # The below echo is re-directed to variable and not printed.
+    echo $userData
+}
+
+function fetch_machine_class(){
+    MCC_NAME=$(kubectl --kubeconfig=dev/seed_kubeconfig.yaml get mcc -n shoot--mcm-ci--$TEST_SHOOT -o custom-columns=Name:.metadata.name --no-headers | grep shoot--mcm-ci)
+    kubectl --kubeconfig=dev/seed_kubeconfig.yaml get mcc $MCC_NAME -n shoot--mcm-ci--$TEST_SHOOT -oyaml > ${SOURCE_PATH}/dev/v1machineclass_converted.yaml
+    yq eval 'del(.metadata.creationTimestamp) | del(.metadata.finalizers) | del(.metadata.generation) | del(.metadata.resourceVersion) | del(.metadata.uid) | del(.credentialsSecretRef)'  dev/v1machineclass_converted.yaml -i
+    yq eval '.metadata.name = "test-mc-v1" | .metadata.namespace = "default" | .secretRef.name = env(TEST_CREDS_SECRET) | .secretRef.namespace = "default"' dev/v1machineclass_converted.yaml -i
+}
+
+function fetch_credentials(){
+   kubectl --kubeconfig=dev/sa_kubeconfig.yaml get secret $CREDENTIALS_SECRET_NAME -n $GARDEN_CORE_NAMESPACE -o yaml > dev/credentials.yaml
+   clientID=$(yq eval '.data.clientID' dev/credentials.yaml)
+   clientSecret=$(yq eval '.data.clientSecret' dev/credentials.yaml)
+   subscriptionID=$(yq eval '.data.subscriptionID' dev/credentials.yaml)
+   tenantID=$(yq eval '.data.tenantID' dev/credentials.yaml)
+
+   # The below echo is re-directed to variable and not printed.
+   echo "$clientID" "$clientSecret" "$subscriptionID" "$tenantID"
+}
+
+function create_test_mc_secret() {
+    read clientID clientSecret subscriptionID tenantID < <(fetch_credentials)
+    userData=$(fetch_userdata)
+    rm -f dev/credentials.yaml
+    rm -f dev/userData.yaml
+secret_yaml=$(cat <<EOF
+apiVersion: v1
+data:
+  clientID: $clientID
+  clientSecret: $clientSecret
+  subscriptionID: $subscriptionID
+  tenantID: $tenantID
+  userData: $userData
+kind: Secret
+metadata:
+  name: $TEST_CREDS_SECRET
+  namespace: default
+type: Opaque
+EOF
+)
+    echo "Creating test_mc_secret..."
+    echo "$secret_yaml" | kubectl --kubeconfig=$CONTROL_KUBECONFIG apply -f -
+    local exec_result=$?
+    echo "test_mc_secret create result: $exec_result"
+    if [[ exec_result -ne 0 ]]; then
+        printf "create_test_mc_secret failed with error: $exec_result" >&2
+        exit $exec_result
+    fi
+}
+
+function delete_test_mc_secret() {
+    kubectl --kubeconfig=$CONTROL_KUBECONFIG delete secret $TEST_CREDS_SECRET
+}
+
+function  cleanup_environment() {
+    printf "\n\t\t\t----- Deleting the test_mc_secret --------\n"
+    delete_test_mc_secret
 }
 
 function setup_environment() {
@@ -117,21 +198,30 @@ function setup_environment() {
     setup_ginkgo
     fi
     
-    #fetching kubeconfigs and machineClass from secret_server
-    fetch_control_kubeconfig
-    fetch_target_kubeconfig
+    fetch_service_account_kubeconfig
+    fetch_oot_cluster_kubeconfig
+    create_test_mc_secret
+    echo "test-mc-secret created successfully"
     fetch_machine_class
+    echo "machineclass fetched successfully"
 }
+
+function fetch_existing_nodes() {
+    kubectl --kubeconfig=$TARGET_KUBECONFIG get nodes --no-headers | wc -l
+}
+
 
 function check_cluster_state() {
     printf "\t\t\t----- Checking Test Environment -------\n"
 
-    printf "\nChecking existance of machine crds\n"
+    printf "\nChecking existence of machine crds\n"
     # Wait 60mins for any existing PRs to cleanup machine crds, as crd cleanup is last step.
     hf_wait_on "hf_num_of_objects" crd 0 3600
     printf "No machine crds in control test cluster\n"
 
-    printf "\nChecking existance of node objects\n"
+    printf "\nChecking existence of node objects\n"
+    num_of_existing_nodes=$(($(fetch_existing_nodes)))
+    printf "\nexisting_default_nodes=$num_of_existing_nodes\n"
     # Wait 60mins for any existing PRs to cleanup nodes
     hf_wait_on "hf_num_of_ready_nodes" nodes 0 3600
     printf "No additional node objects in target test cluster\n"
@@ -148,10 +238,13 @@ function check_cluster_state() {
 ############################################## <Modules> ########################################################
 
 function run_integration_tests() {
+    echo "Printing env.."
+    env
+    echo "---"
     echo "Starting integration tests..."
     set +e
 
-    ginkgo -v -mod=vendor test/integration/controller
+    ginkgo -v --show-node-events --poll-progress-after=480s --poll-progress-interval=90s test/integration/controller
     TEST_RESULT=$?
     
     set -e
@@ -187,9 +280,10 @@ if [ ${result} -ne 0 ]; then
 exit $result
 fi
 run_integration_tests
+cleanup_environment
 print_controller_logs
 printf "\n\t\t\t----- End of Test Script -----------\n"
-
+printf "\n\t\t\t----- Exiting with TEST_RESULT: %s -----------\n" "$TEST_RESULT"
 exit $TEST_RESULT
 
 ############################################## </Main> ########################################################
